### ISSUE TITLE
IRSA Custom Resource "delete role" operation fails

### ISSUE THREAD

**Issue by max-boehm** [awslabs/amazon-eks-irsa-cfn#8]
When using the IRSA Custom Resource in a CloudFormation template I get an error when deleting the stack. Example:

```
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ClusterName:
    Description: EKS cluster name
    Type: String

Resources:
  IAMRole:
    Type: Custom::ServiceAccountRole
    Properties:
      RoleName: !Sub "${ClusterName}-default-role"
      ServiceToken: !ImportValue EKSIRSARoleCreationFunction
      ClusterName: !Ref ClusterName
      ServiceAccount: default
      Namespace: default
      ManagedPolicyArns:
        - !Ref IAMPolicy
  IAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: IAM policy for the service account
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: s3:*
            Resource: '*'
```

When deleting the stack I get:
```
Received response status [FAILED] from custom resource. Message returned: Cannot delete entity, must detach all policies first. (RequestId: ef5d25cc-8883-4d0c-a24e-9ccb35a221b8)
```

I think the `deleteRole()` function in the lambda handler needs to detach the role policies first. I had created a PR with a fix, but it has not been discussed and was just closed, see https://github.com/awslabs/amazon-eks-irsa-cfn/pull/7.
